name: dental_umg
description: Aplicación móvil para consejos y análisis dental
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0
  
  # Geolocalización y Mapas - OpenStreetMap
  geolocator: ^11.0.0           # Última versión para obtener ubicación
  permission_handler: ^11.3.0   # Manejo de permisos
  flutter_map: ^6.1.0           # Mapas con OpenStreetMap
  latlong2: ^0.9.0              # Manejo de coordenadas
  http: ^1.2.0                  # Para consultas a Overpass API
  url_launcher: ^6.2.4          # Abrir enlaces externos
  
  # Formateo de fechas
  intl: ^0.19.0
  
  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true