//firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS1K7aFf_2SQyMQy-FvPTYMlBW8lzVVFM',
    appId: '1:287875927706:web:aa90697b26ecb1550d5923',
    messagingSenderId: '287875927706',
    projectId: 'dentalai-5915',
    authDomain: 'dentalai-5915.firebaseapp.com',
    storageBucket: 'dentalai-5915.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsQ25c_neosOUas2soKh_OSNWriPRsWfc',
    appId: '1:287875927706:android:abb71c472df3a1e60d5923',
    messagingSenderId: '287875927706',
    projectId: 'dentalai-5915',
    storageBucket: 'dentalai-5915.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QAqeVNjco73kwqS0P8KqJYzy9heQdVE',
    appId: '1:287875927706:ios:ece7b06b05a8a49a0d5923',
    messagingSenderId: '287875927706',
    projectId: 'dentalai-5915',
    storageBucket: 'dentalai-5915.firebasestorage.app',
    iosBundleId: 'com.example.dentalUmg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1QAqeVNjco73kwqS0P8KqJYzy9heQdVE',
    appId: '1:287875927706:ios:ece7b06b05a8a49a0d5923',
    messagingSenderId: '287875927706',
    projectId: 'dentalai-5915',
    storageBucket: 'dentalai-5915.firebasestorage.app',
    iosBundleId: 'com.example.dentalUmg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS1K7aFf_2SQyMQy-FvPTYMlBW8lzVVFM',
    appId: '1:287875927706:web:1403f509acd93ca20d5923',
    messagingSenderId: '287875927706',
    projectId: 'dentalai-5915',
    authDomain: 'dentalai-5915.firebaseapp.com',
    storageBucket: 'dentalai-5915.firebasestorage.app',
  );
}
